# -*- coding: utf-8 -*-
"""All library mod 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/180IC0mT-afce4VyrfhWZnzm-9MAoQWG1
"""

import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
a=np.zeros((3,3))
print(a)
b=np.ones((3,3))
print(b)
c=np.arange(10)
print(c)
#manuplations
arr_reshaped=arr.reshape(5,1)
print(arr_reshaped)
arr_sliced=arr[2:4]
print(arr_sliced)

arr1=np.array([1,2,3,4])
arr2=np.array([6,7,8,9])
add=(arr1+arr2) #elementary operations
print(add)
print(arr1+3) #broadcasting



#vertical
arr1=np.array([1,2,3,4])
arr2=np.array([6,7,8,9])
stack=np.vstack(arr1+arr2)
print(stack)

#horizontal
arr1=np.array([1,2,3,4])
arr2=np.array([6,7,8,9])
stack=np.stack(arr1+arr2)
print(stack)

#split
arr1=np.array([1,2,3,4,5,6])
arr2=np.split(arr1,2)
print(arr2)

#transpose
arr1=np.array([[1,2,3],[4,5,6]])
arr2=arr1.T
print(arr1)
print(arr2)

#linear algebra using numpy
arr1=np.array([[1,2],[5,6]])
arr2=np.array([[2,3],[4,5]])
arr3=np.dot(arr1,arr2)
d=np.linalg.eig(arr3)
print(d)

import numpy as np
arr1=np.array([[1,2,3],[4,5,6,]])
arr2=np.array([[1,2,3],[4,5,6,]])
arr3=np.sum(arr1,axis=0)#column wise
print(arr3)
arr4=np.sum(arr1,axis=1)#row wise
print(arr4)

a=np.array([[2,3,4],[1,3,5]])
c=np.sum(a, axis=0)
d=np.sum(a, axis=1)
print(a)

#statistical
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([[1,2,3],[4,5,6,]])
print("mean",np.mean(arr1))
print("median",np.median(arr1))
print("variance",np.var(arr1))
print("standard deviation",np.std(arr1))

#file loading
data=np.loadtxt("/content/bhushan.txt",dtype=int)
#data=np.savetxt("/content/date.txt",data)
print(data)

import pandas as pd
a=["jwalitha","ramya","durga","jahnavi","lahari","sunny","dhanush"]
r=pd.Series(a,index=[67,43,44,89,34,45,23])
print(r)

df=pd.read_csv("/content/text.csv")
print(df)

df=pd.read_excel("/content/Coca Cola Co.xlsx")
print(df)

df=pd.read_csv("/content/train.csv")
print(df)

rom google.colab import drive
drive.mount('/content/drive')

import pandas as pd
df = pd.read_csv("/content/text.csv")
print(df.shape)
a=df.head(10)
b=df.tail(10)
c=pd.concat([a,b])
c.to_csv('raj.csv')
print(c.groupby(['emotion'])['text'].count())

!pip install pandas
import pandas as pd

# Read the CSV file into a DataFrame
df = pd.read_csv("/content/text.csv")

# Print the first 10 rows of the DataFrame


# Print the last 10 rows of the DataFrame

# Concatenate the first and last 10 rows of the DataFrame
c = pd.concat([df.head(10), df.tail(10)])

# Save the concatenated DataFrame to a CSV file
c.to_csv('raj.csv')

# Group the DataFrame by the 'emotion' column and count the number of rows in each group
print(c.groupby(['emotion'])['text'].count())

import numpy as np
import matpimportlotlib.pyplot as plt
runs=np.array([100,50,91,78,89,25,34,19,9,10])
w=np.array([1,0,2,0,3,7,8,9,7,5])
plt.plot(runs,w,color='orange')
plt.title('IndvsAus_score')
plt.show()

import matplotlib.pyplot as plt
tiger=np.linspace(-2*np.pi,2*np.pi,50)
print(tiger)

plt.scatter(tiger,np.sin(tiger),color='red')
plt.title("sin(x)")

import numpy as np
import matplotlib.pyplot as plt
overs=np.arange(5,50,5)
overs_a=np.arange(5,30,5)

runs_i=np.array([25,51,84,131,160,189,220,250,267])
runs_a=np.array([15,41,94,110,151])
wickets=np.array([12,32,96])
plt.subplot(2,1,2)
plt.plot(overs,runs_i,color='blue',label='India')
plt.subplot(2,1,1)
plt.plot(overs_a,runs_a,color='yellow',label='Aus')
plt.legend(loc='best')
plt.show()

import matplotlib.pyplot as plt
a=[230,560,780,127,128]
b=[200,160,270,127,400]
years=[1,2,3,4]
profit_a=[(a[i]-a[i-1])for i in range(1,len(a))]
profit_b=[(b[i]-b[i-1])for i in range(1,len(b))]
plt.subplot(2,1,2)
plt.plot(years,profit_a,color='pink',linewidth='2',label='Company',marker='*',ms='15',mec='r')
plt.subplot(2,1,1)
plt.plot(years,profit_b,color='black',linestyle='dotted',label='Company',ms='10',marker='>')
plt.show()

import numpy as np
import matplotlib.pyplot as plt
a=np.array([25,60,5,10])
labe=["AIML","Python","Pandas","Numpy"]
plt.pie(a, labels=labe, colors=['pink', 'green', 'blue', 'black'])
plt.show()

import numpy as np
import matplotlib.pyplot as plt
a=np.array([25,60,5,10])
labe=["AIML","Python","Pandas","Numpy"]
explo=[0.2,0,0,0]
plt.pie(a,labels=labe,explode=explo,startangle=180,colors=['violet', 'brown','skyblue', 'yellow'])
plt.show()

#load example dataset
import seaborn as sns
import matplotlib.pyplot as plt
datasets=sns.load_dataset("/content/temp..xlsx")
sns.scatterplot(x="Inside Temperature",y="Date",data=datasets)
plt.title("scatter plot of Inside Temperature vs.Date")
plt.xlabel("Inside Temperature ($)")
plt.ylabel("Date($)")
plt.show()

#load example dataset
import seaborn as sns
import matplotlib.pyplot as plt
tips=sns.load_dataset("tips")
sns.scatterplot(x="total_bill",y="tip",data=tips)
plt.title("scatter plot of Toatl Bill vs.Tip")
plt.xlabel("Toatl Bill ($)")
plt.ylabel("Tip($)")
plt.show()

#load example dataset
import seaborn as sns
import matplotlib.pyplot as plt
tips=sns.load_dataset("planets")
tips.head()
sns.scatterplot(x="mass",y="year",data=tips)
plt.title("scatter plot of mass vs. year")
plt.xlabel("mass ($)")
plt.ylabel("year($)")
plt.show()

import matplotlib.pyplot as plot
iris=sns.load_dataset("iris")
correlation_matrix=iris.corr()
sns.heatmap(correlation_matrix,annot=True,cmap="coolwarm")
plt.title("correlation heatmap of Iris Dataset")
plt.show()

import matplotlib.pyplot as plot
diamonds=sns.load_dataset("diamonds")
correlation_matrix=diamonds.corr()
sns.heatmap(correlation_matrix,annot=True,cmap="coolwarm")
plt.title("correlation heatmap of diamonds Dataset")
plt.show()